# Generated by Django 4.2.5 on 2023-09-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="person",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="person",
            name="age",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
