# Generated by Django 4.2.5 on 2023-09-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0002_rename_first_name_person_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="interest",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
