# Generated by Django 4.2.5 on 2023-09-14 11:49

from django.db import migrations, models
import persons.models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0003_person_interest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="age",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                validators=[persons.models.validate_string],
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.CharField(
                blank=True,
                max_length=254,
                null=True,
                validators=[persons.models.validate_string],
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="house_address",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                validators=[persons.models.validate_string],
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="interest",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[persons.models.validate_string],
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                validators=[persons.models.validate_string],
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="occupation",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[persons.models.validate_string],
            ),
        ),
    ]
